package com.twu.tictactoe;

import org.junit.Test;

import java.io.PrintStream;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.*;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'msloane' at '8/6/15 1:19 PM' with Gradle 2.5
 *
 * @author msloane, @date 8/6/15 1:19 PM
 */
public class TicTacToeGameTest {
    @Test public void shouldDrawBoardWhenGameStarts() {
        PrintStream printStream = mock(PrintStream.class);

        TicTacToeGame game = new TicTacToeGame();
        assertThat(game.drawBoard(), is("   |   |   \n" +
                                        "---------\n" +
                                        "   |   |   \n" +
                                        "---------\n" +
                                        "   |   |   \n"));
    }

    @Test public void shouldRedrawBoardWhenMoveExecuted() {
        PrintStream printStream = mock(PrintStream.class);
        Player p1 = mock(Player.class);
        when(p1.toString()).thenReturn("X");

        TicTacToeGame game = new TicTacToeGame();
        assertThat(game.redrawBoard(1, p1), is(" X |   |   \n" +
                "---------\n" +
                "   |   |   \n" +
                "---------\n" +
                "   |   |   \n"));
    }
}
