package com.twu.tictactoe;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'msloane' at '8/6/15 1:19 PM' with Gradle 2.5
 *
 * @author msloane, @date 8/6/15 1:19 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
