package com.twu.tictactoe;

import java.util.ArrayList;
import java.util.HashSet;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'msloane' at '8/6/15 1:19 PM' with Gradle 2.5
 *
 * @author msloane, @date 8/6/15 1:19 PM
 */
public class TicTacToeGame {

    private String horizontalDivider = "---------\n";
    private ArrayList<String> graphicMoves;
    private HashSet<Integer> moves;

    public TicTacToeGame () {
        graphicMoves = new ArrayList<>();
        moves = new HashSet<>();
        graphicMoves.add("   |   |   \n");
        graphicMoves.add("   |   |   \n");
        graphicMoves.add("   |   |   \n");
    }

    public String drawBoard() {
        return graphicMoves.get(0) + horizontalDivider + graphicMoves.get(1) + horizontalDivider + graphicMoves.get(2);
    }

    public String redrawBoard(int x, Player player) {
        StringBuilder newRow = new StringBuilder(graphicMoves.get(getRow(x)));
        newRow.setCharAt(getColStringLocation(x), player.toString().charAt(0));
        graphicMoves.set(getRow(x), newRow.toString());
        moves.add(x);
        return drawBoard();
    }

    private int getRow(int x) {
        if (x > 6){
            return 2;
        } else if (x > 3) {
            return 1;
        } else {
            return 0;
        }
    }

    private int getColStringLocation(int x) {
        if (x % 3 == 0) {
            return 9;
        } else if (x % 3 == 2) {
            return 5;
        } else {
            return 1;
        }
    }


    public boolean isValidMove(int i) {
        return !moves.contains((Integer)i);
    }

    public boolean boardIsFull() {
        return (moves.size() == 9);
    }
}
